# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
    - -X github.com/instructure-bridge/truss-cli/cmd.Version={{.Version}}
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    name: truss-cli
    description: CLI to help manage many k8s clusters
    homepage: https://github.com/instructure-bridge/truss-cli
    github:
      owner: instructure-bridge
      name: homebrew-tap
    folder: Formula
    dependencies:
      - name: kubectl
      - name: vault
      - name: sshuttle
    test: |
      system "bin/truss", "help"
    install: |
      system "cp", "truss-cli", "truss"
      bin.install "truss"
