before:
  hooks:
    - go mod download
    - go generate ./...

builds:
- env:
  - CGO_ENABLED=0
  ldflags:
    - -X github.com/get-bridge/truss-cli/cmd.Version={{.Version}}
  binary: truss
  goos:
    - darwin
    - linux
  goarch:
    - amd64
    - arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    name: truss-cli
    description: CLI to help manage many k8s clusters
    homepage: https://github.com/get-bridge/truss-cli
    tap:
      owner: get-bridge
      name: homebrew-tap
    folder: Formula
    dependencies:
      - name: kubectl
      - name: vault
      - name: sshuttle
    test: |
      system "bin/truss", "help"
    install: |
      bin.install "truss"
