before:
  hooks:
    - go mod download
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
    - -X github.com/get-bridge/truss-cli/cmd.Version={{.Version}}
  binary: truss
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    name: truss-cli
    description: CLI to help manage many k8s clusters
    homepage: https://github.com/get-bridge/truss-cli
    tap:
      owner: get-bridge
      name: homebrew-tap
    folder: Formula
    dependencies:
      - name: kubectl
      - name: vault
      - name: sshuttle
    test: |
      system "bin/truss", "help"
    install: |
      bin.install "truss"
