# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    tags: ['*']

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Unshallow required for goreleaser's changelog behavior
    - name: Unshallow
      run: git fetch --prune --unshallow

    # Go get'em!
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    # Release the thing!
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.INSTRUCTURE_BRIDGE_GITHUB_BOT_REPO_RW }}

  # The publish job will publish the bootstrap-templates directory to the correct S3 Bucket
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl private --follow-symlinks
      env:
        # Credentials for this workflow are provisioned in the `terraform` directory
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: truss-cli-global-config
        AWS_REGION: us-east-2
        SOURCE_DIR: bootstrap-templates
        DEST_DIR: bootstrap-templates